"""table

Revision ID: 07bd298f7969
Revises: 
Create Date: 2021-01-08 14:05:40.142020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07bd298f7969'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_all',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rich_id', sa.String(length=30), nullable=False),
    sa.Column('rich_name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_rich_push',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rich_id', sa.String(length=150), nullable=False),
    sa.Column('rich_name', sa.String(length=60), nullable=True),
    sa.Column('rich_scope', sa.String(length=10), nullable=True),
    sa.Column('rich_code', sa.String(length=100), nullable=True),
    sa.Column('rich_time', sa.String(length=100), nullable=True),
    sa.Column('rich_status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_rich_push')
    op.drop_table('t_all')
    # ### end Alembic commands ###
